name: Rebuild image

permissions:
  id-token: write
  contents: read
on:
  schedule:
    - cron: '47 4 1 * *'
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/build-image.yml
    secrets: inherit
    with:
      image-name: ${{ vars.DOCKER_IMAGE_NAME }}

