---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - secrets/status
  verbs:
  - get
- apiGroups:
  - solr.apache.org
  resources:
  - solrclouds
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - solr.dgicloud.com
  resources:
  - users
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - solr.dgicloud.com
  resources:
  - users/finalizers
  verbs:
  - update
- apiGroups:
  - solr.dgicloud.com
  resources:
  - users/status
  verbs:
  - get
  - patch
  - update
